[package]
name = "hort_mc"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3


[dependencies]
gl = "0.14.0"
std140 = "0.2.6"
image = "0.24.6"

[dependencies.sdl2]
version = "0.35.2"
features = ["bundled", "static-link"]